### ISSUE TITLE
White text on white background in Azul

### ISSUE THREAD

**Issue by alexandreleroux** [bastien09/bga-dark-theme#19]
See attached screenshot, issue with white text on white background in Azul. Thanks for this wonderful theme, it really should be officially provided by BGA!

<img width="1206" alt="Image" src="https://user-images.githubusercontent.com/874004/148692566-f212be70-443d-4d0b-9208-250c26ab01a3.png">

**Comment by lehenry** [comment]
When does this bubble appear? It looks like something that would appear on hovering the zoom buttons, but I don't see anything like this.

**Comment by lehenry** [comment]
Never mind, I found it, and it has a "disable zoom notice" option in there that I must have checked once.
