### ISSUE TITLE
Cannot access bug page due to dark theme CSS

### ISSUE THREAD

**Issue by alexandreleroux** [bastien09/bga-dark-theme#2]
First, big thanks for this BGA dark theme. Just started using it and loving it so far.

Potential bug when this CSS is enabled:
* go to https://boardgamearena.com/bug?id=14660
* resulting error message:
```
Désolé, une erreur inattendue s'est produite...

You cannot access this section because you are using some custom CSS (see Preferences > Advanced)

>> Sortez-moi d'ici <<
```

Thanks! :-)

**Comment by bastien09** [comment]
Hello, glad to see you're appreciating this dark theme :-)

In fact what you are reporting is a normal behavior, BGA team is deliberately forbidding you to access bug report sections if you're using a custom theme, so they are sure the bug you are reporting comes from BGA and not from the theme you are using.

If you want to access bug reporting section you need to disable custom theme, by emptying the text box in Preferences -> Advanced, or, if you only want to read, you can open these links in private browsing.

**Comment by alexandreleroux** [comment]
Good point @bastien09 . I thought it was working for some bug pages, but apparently only works for bug listing pages, not individual bug report pages.

Sorry for the noise and thanks again for the custom dark mode :-)
