### ISSUE TITLE
Viticulture issue : white text in white boxes

### ISSUE THREAD

**Issue by alexandreleroux** [bastien09/bga-dark-theme#3]
Thanks for the theme :-)

There's an issue with the Viticulture game, where there is white text in white boxes. We thus can't see the text (but can select it). This happens at least for the 'count of cards' and the 'year and season info', as seen in the attached screenshot.

Merci !

![Image 2021-11-07 à 10 38](https://user-images.githubusercontent.com/874004/140651933-07ca5b57-2e9c-473c-afe9-f55cafb96cc8.jpg)

**Comment by bastien09** [comment]
Thanks for reporting @alexandreleroux, I'll fix this bug in the next update!

**Comment by alexandreleroux** [comment]
confirmed fixed @bastien09 , big thanks! :-)

**Comment by bastien09** [comment]
> confirmed fixed @bastien09 , big thanks! :-)

Thanks to @lehenry who fixed this issue 😉
