### ISSUE TITLE
Monospaced fonts for in-game notes?

### ISSUE THREAD

**Issue by shervinsahba** [bastien09/bga-dark-theme#57]
This isn't dark mode per se, but would you know how to enforce monospaced fonts for the in-game notes via CSS?

![](https://i.imgur.com/gPI11nE.png)

**Comment by lehenry** [comment]
You can just add the following at the end of your custom profile CSS
```
#turnbased_notes_content{
 font-family:  Courier New;
}
```

**Comment by shervinsahba** [comment]
Wow, it was that simple. Thanks, this was instructive!
